src/Entity/Movie.php
<?php

namespace App\Entity;

use App\Repository\MovieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MovieRepository::class)]
class Movie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $release_date = null;

    #[ORM\Column(length: 255)]
    private ?string $director = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $genre = null;

    #[ORM\Column]
    private ?int $length = null;

    #[ORM\Column(length: 255)]
    private ?string $path = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_path = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->release_date;
    }

    public function setReleaseDate(\DateTimeInterface $release_date): static
    {
        $this->release_date = $release_date;

        return $this;
    }

    public function getDirector(): ?string
    {
        return $this->director;
    }

    public function setDirector(string $director): static
    {
        $this->director = $director;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getLength(): ?int
    {
        return $this->length;
    }

    public function setLength(int $length): static
    {
        $this->length = $length;

        return $this;
    }

    public function getPath(): ?string
    {
        return $this->path;
    }

    public function setPath(string $path): static
    {
        $this->path = $path;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->image_path;
    }

    public function setImagePath(?string $image_path): static
    {
        $this->image_path = $image_path;

        return $this;
    }
}

templates/Page/create.html.twig
{% extends 'Layout/base.html.twig' %}

{% block title %}Register{% endblock title %}

{% block body %}
    <div data-bs-theme="light">
        <div class="bg-body d-flex text-center justify-content-center align-items-center min-vh-100">
            {{ form_start(form, { 'attr': {'class': 'form w-25 pb-5 mb-5'} }) }}

            <h1 class="pb-4">Add a movie</h1>

            <div class="input-group mb-3">
                {{ form_widget(form.title, {'attr': {'class': 'form-control', 'placeholder': 'Enter a title'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.release_date, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.director, {'attr': {'class': 'form-control', 'placeholder': 'Enter a director'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.genre, {'attr': {'class': 'form-control', 'placeholder': 'Enter a genre'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.length, {'attr': {'class': 'form-control', 'placeholder': 'Enter a length'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.poster, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="input-group mb-3">
                {{ form_widget(form.movie, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-outline-danger">Register</button>
            </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock body %}

templates/Page/index.html.twig
{% extends 'Layout/base.html.twig' %}

{% block body %}
    <div data-bs-theme="light">
        <div class="min-vh-100 min-vw-100">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="">
                        <b>Netflux</b>
                    </a>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-danger" type="submit">Search</button>
                    </form>
                    <ul class="navbar-nav">
                        {% if admin == 1 %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ path("add") }}">Ajouter</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ path("logout") }}">Déconnexion</a>
                        </li>
                    </ul>
                </div>
            </nav>

            <div class="container-fluid bg-body pt-5 pb-4 mx-0">
                <div class="container d-flex flex-row justify-content-center flex-wrap text-center">
                    {% for film in films %}
                        <div class="card mx-4 mb-5 hover-shadow" style="width: 15rem;">
                            <img src="{{ asset("medias/" ~ film.imagePath) }}" class="card-img-top" alt="{{ film.title }}">
                            <div class="card-footer">
                                <a href="{{ path("watch", {'id': film.id}) }}">
                                    <button type="button" class="btn btn-outline-danger" style="width: 12rem;">Regarder</button>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/Page/watch.html.twig
{% extends 'Layout/base.html.twig' %}

{% block body %}
    <div data-bs-theme="light">
        <div class="min-vh-100 min-vw-100">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{{ path('index') }}">
                        <b>Netflux</b>
                    </a>
                </div>
            </nav>

            <div>
                <video controls>
                    <source src="{{ asset("medias/" ~ film.imagePath) }}" type="video/webm" />
                    <source src="{{ asset("medias/" ~ film.Path) }}" type="video/mp4" />
                </video>
            </div>
        </div>
    </div>
{% endblock body %}